configname: config_oceans.yaml
epochs: 10
trials: 5
n_jobs: 2
dataset_folder: ./data/
dataset: [oceans_challenge] # data/Jan_data, data/Feb_data data/Mar_data
method: [fourier, siren, wires] # [--siren, --fourier, ""]
normalise: [normalise, ""]
lr: #log search
  - 1.e-5 # min
  - 1.e-1 # max
bs: # power of 2 search
  - 9 # 512 # min
  - 13 # 2048 # max
scale: # power of 2 search
  - 0 # min
  - 8 # max
mapping_size: # power of 2 search
  - 7 # min
  - 11 # max
lambda_range: #log search # For both xy and t
  - 1.e-5 # min
  - 1.e+1 # max
hidden_num: # log search for SIREN and WIRES
  - 4
  - 12
hidden_dim: 
  - 6
  - 12
do_skip: [1]
width_gaussion: # log search for WIRES only
  - 1
  - 6
act: [tanh]
arch: [skip-5] # log search for RFF only
verbose: 1