datapath: /Data/pnaylor/data_ice_sheet
datapath_validation: /Data/pnaylor/data_ice_sheet_validation
data_setup: mini #small # mini, small, medium, all
coherence: [On, Off]
swath: [On, Off]
dem: [On, Off]
pde_curve: [Off]
optuna: On
inr_config: inr-config.yaml
pre_processing_config: pre_processing-config.yaml
dem_contours_config: dem-contours-config.yaml
