datapath: /Users/peter.naylor/Downloads/IceSheet/data
data_setup: mini
coherence: [On, Off]
swath: [On, Off]
dem: [On, Off]
inr_config: inr-config.yaml
pre_processing_config: pre_processing-config.yaml
