# Coherence
exclude_coherence: On
coherence_threshold: 0.7
# Outlier detection based on STD
exclude_outliers: On
exclude_std_multiple: 3. #number of std which is a threshold
grid_size: 10000
overlay: 0.5
time_step: 365
