name: medium_size
datapath: /Data/pnaylor/data_ice_sheet
datapath_validation: /Data/pnaylor/data_ice_sheet_validation
data_setup: medium #small # mini, small, medium, all
model: [SIREN, RFF] #, RFF, SIREN, MFN] # WIRES KAN
coherence: [Off] #[Off] # [On, Off] #[On, Off]
swath: [On] #[Off] # [On, Off] #[On, Off]
dem: [Off] #[Off] # [On, Off] #[On, Off]
pde_curve: [Off]
inr_config: inr-config.yaml
pre_processing_config: pre_processing-config.yaml
dem_contours_config: dem-contours-config.yaml
